# docker-compose.yml
version: '3.8'

services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    ports:
      - "10000:10000" # Blob service
      - "10001:10001" # Queue service
      - "10002:10002" # Table service
    volumes:
      - ./volumes/azurite:/data
    command: "azurite --loose --blobHost 0.0.0.0 --blobPort 10000 --queueHost 0.0.0.0 --queuePort 10001 --tableHost 0.0.0.0 --tablePort 10002 --location /data --debug /data/debug.log"
    #command: "azurite --location /data --debug /data/debug.log"
  cosmosdb:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
    container_name: cosmosdb-emulator
    ports:
      - "8081:8081"   # HTTPS endpoint
      - "10251-10255:10251-10255"
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=2
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
      - AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=0.0.0.0
    tty: true
    privileged: true
    volumes:
      - ./volumes/cosmos:/data

# Usage:
#   docker-compose up -d
# Azurite will be available on ports 10000-10002.
# Cosmos DB Emulator will be available on port 8081 (HTTPS).